/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.kotlin-common-conventions")

    // Apply the application plugin to add support for building a CLI application in Java.
    application


    id("org.springframework.boot")

    // id("org.jetbrains.kotlin.plugin.jpa")
    kotlin("plugin.jpa")
    kotlin("plugin.spring")

    // id("org.jetbrains.dokka")
}

// apply(plugin = "org.jetbrains.kotlin.plugin.jpa")

// Type safe dependency accessors aren't accessible within 'buildSrc/src/main/kotlin'.
val libs = extensions.getByType<VersionCatalogsExtension>().named("libs")

dependencies {
  // Removes the need to specify the Spring Boot BOM in every Spring Boot project.
  implementation(platform(libs.findLibrary("spring-boot-dependencies").get()))
}