/*
 * This file was generated by the Gradle 'init' task.
 */
import org.springframework.boot.gradle.plugin.SpringBootPlugin

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`

    id("org.springframework.boot") version "3.5.4"
    id("org.jetbrains.kotlin.plugin.jpa") version "1.9.25"
    id("org.jetbrains.kotlin.plugin.spring") version "1.9.25"

	// kotlin("plugin.spring") version "1.9.25"
	// id("org.springframework.boot") version "3.5.4"
	id("io.spring.dependency-management") version "1.1.7"
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()

    // https://plugins.gradle.org/plugin/org.springframework.boot
    maven {
        url = uri("https://plugins.gradle.org/m2/")
    }
}

dependencies {
    implementation(libs.kotlin.gradle.plugin)

    implementation(platform(SpringBootPlugin.BOM_COORDINATES))

    implementation("org.springframework.boot:spring-boot-gradle-plugin:3.5.4")
    implementation("org.jetbrains.kotlin:kotlin-noarg:1.9.25")
    implementation("org.jetbrains.kotlin:kotlin-allopen:1.9.25")
}
